################################################         
# Headers 
################################################

AWSTemplateFormatVersion: 2010-09-09
Description: "Sample CloudFormation Template."

################################################         
# Parameters
################################################

Parameters:
 
  MyKeyPair:
    Type : AWS::EC2::KeyPair::KeyName
    Description:
      "Select a key pair from the dropdown to deploy FW with."
 
  IPAddress:
    Type: String
    Description:
      "Enter your IP Address here (ex. 0.0.0.0/32)"
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.

################################################         
# Mappings
################################################

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0de53d8956e8dcf80
    us-west-2:
      AMI: ami-061392db613a6357b

################################################         
# Resources
################################################
  
Resources:

################################################         
# Instances
################################################

  MyInstance:
    Type: AWS::EC2::Instance                    
    Properties:
      SecurityGroupIds: [!Ref MySecurityGroup]
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: t2.micro
      KeyName: !Ref MyKeyPair
      Tags: 
        - Key: Name
          Value: Sample Instance
      UserData:
        Fn::Base64:
          !Sub |
              #!/bin/bash -ex
              echo ${AWS::Region} > /tmp/region.txt;

################################################         
# SecurityGroups 
################################################

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open necessary ports for SSHing
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref IPAddress
