AWSTemplateFormatVersion: "2010-09-09"

Resources:
###########################################
  # Sample created EC2 with Security Group #

  # MyEc2Instance:
  #   Type: 'AWS::EC2::Instance'
  #   Properties:
  #     SecurityGroups: [!Ref MySecurityGroup]
  #     KeyName: sample2
  #     ImageId: ami-0de53d8956e8dcf80
  #     InstanceType: t2.micro
  #     Tags:
  #       - Key: Name
  #         Value: Sample
  #     IamInstanceProfile: !Ref MyEC2InstanceRole
  # MySecurityGroup:
  #   Type: 'AWS::EC2::SecurityGroup'
  #   Properties:
  #     GroupDescription: SSH Access
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: 199.66.91.253/32

###########################################

  # MyS3Bucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: mybucket007lolololol1

###########################################
  # CFInstanceRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - ec2.amazonaws.com
  #           Action:
  #             - sts:AssumeRole
  #     Path: "/"

  # MyEC2Policy:
  #   Type: AWS::IAM::Policy
  #   Properties:
  #     PolicyName: MyPolicy
  #     PolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Action: "s3:*"
  #           Resource: !Join ['', ['arn:aws:s3:::', !Ref MyS3Bucket]]
  #           #Resource: "*"
  #     Roles: 
  #       - !Ref CFInstanceRole

  # MyEC2InstanceRole:
  #   Type: AWS::IAM::InstanceProfile
  #   Properties: 
  #     Roles:
  #       - !Ref CFInstanceRole
  #     InstanceProfileName: ectworoletest

###########################################