################################################         
# Headers 
################################################

AWSTemplateFormatVersion: 2010-09-09
Description: "Sample CloudFormation Template."

################################################         
# Resources
################################################

# VPC

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Demo

################################################

# Subnets

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: PublicSubnet
      VpcId: !Ref MyVPC

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet
      VpcId: !Ref MyVPC

################################################